version: "3.8"
services:
  jobmanager:
    image: flink:latest
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    volumes:
        - .:/home
  taskmanager:
    image: flink:latest
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    #deploy.replicas: 2
    volumes:
        - .:/home
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4

# kafka:
#    image: moeenz/docker-kafka-kraft:latest
#    restart: always
#    ports:
#      - "9093:9093"
#    environment:
#      - KRAFT_CONTAINER_HOST_NAME=kafka
#      - KRAFT_CREATE_TOPICS=topic-a,topic-b,topic-c
#      - KRAFT_PARTITIONS_PER_TOPIC=3
